version: '2'

services:
  whitelabel-agen-backend-api:
    container_name: whitelabel-agen-backend-api
    image: whitelabel-agen-backend-api:0.0.0.1
    build: .
    ports:
      - 2013:2013
    restart: always